### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by yanggthomas** [gtauzin/metaLBM#1]
Hi, I would like to know the current stage of this project since last commit was 4 years ago. Is GPU version avalible? Could you please provide  any performance benchmark.

**Comment by gtauzin** [comment]
Hi,

Sorry but I have not been working on this library. There is indeed a multi
GPU version and the performance benchmark is available as a part of my PhD
thesis :
http://elpub.bib.uni-wuppertal.de/servlets/DerivateServlet/Derivate-8720/dc1905.pdf

**Comment by yanggthomas** [comment]
Hi, thanks for your reply. This solved my problem.
